[package]
name = "decorum"
version = "0.0.11"
license = "MIT"
readme = "README.md"
authors = ["Sean Olson <olson.sean.k@gmail.com>"]
repository = "https://github.com/olson-sean-k/decorum"
description = "Ordering, equality, hashing, and constraints for floating-point types."
keywords = ["finite", "float", "hash", "nan", "ord"]

[badges]
travis-ci = { repository = "olson-sean-k/decorum" }

[features]
default = ["serialize-serde"]
serialize-serde = ["serde", "serde_derive"]

[dependencies]
num-traits = "0.2.*"

serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
