[package]
name = "decorum"
version = "0.1.0"
license = "MIT"
authors = ["Sean Olson <olson.sean.k@gmail.com>"]
description = "Ordering, equality, and hashing for floating point types."

[features]
default = ["serialize-serde"]
serialize-serde = ["serde"]

[dependencies]
num-traits = "0.1.40"

serde = { version = "1.0", optional = true }
