[package]
name = "decorum"
version = "0.0.8"
license = "MIT"
readme = "README.md"
authors = ["Sean Olson <olson.sean.k@gmail.com>"]
repository = "https://github.com/olson-sean-k/decorum"
description = "Ordering, equality, hashing, and constraints for floating-point types."
keywords = ["eq", "finite", "float", "hash", "nan", "ord", "real"]

[badges]
appveyor = { repository = "olson-sean-k/plexus" }
travis-ci = { repository = "olson-sean-k/plexus" }

[features]
default = ["serialize-serde"]
serialize-serde = ["serde", "serde_derive"]

[dependencies]
derivative = "1.0.*"
num-traits = "0.1.40"

serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
