[package]
name = "decorum"
version = "0.0.2"
license = "MIT"
readme = "README.md"
authors = ["Sean Olson <olson.sean.k@gmail.com>"]
repository = "https://github.com/olson-sean-k/decorum"
description = "Ordering, equality, and hashing for floating point types."
keywords = ["float", "hash", "ord"]

[features]
default = ["enforce-constraints", "serialize-serde"]
enforce-constraints = []
serialize-serde = ["serde"]

[dependencies]
derivative = "1.0.*"
num-traits = "0.1.40"

serde = { version = "1.0", optional = true }
